export interface DietPlan {
  id: string
  condition: string
  category: string
  description: string
  keyFoods: string[]
  avoidFoods: string[]
  keyTip: string
  sampleMeals: {
    meal: string
    foods: string
  }[]
}

export const dietData: DietPlan[] = [
  {
    id: "diabetes-type2",
    condition: "Type 2 Diabetes",
    category: "diabetes",
    description: "A balanced diet using affordable Indian foods to help manage blood sugar levels.",
    keyFoods: [
      "Leafy greens (palak, methi, sarson)",
      "Whole grains (brown rice, daliya, ragi)",
      "Lean proteins (chicken, fish, paneer, eggs)",
      "Legumes (moong dal, chana dal, rajma)",
      "Nuts and seeds (groundnuts, til)",
      "Local fruits (guava, papaya, apple)",
      "Vegetables (karela, bhindi, lauki)",
      "Curd (homemade dahi)",
    ],
    avoidFoods: [
      "Sugary drinks and cold drinks",
      "White rice and maida products",
      "Processed meats and sausages",
      "Deep fried foods (samosa, pakora)",
      "Mithai and sweets",
      "Pickles and papad (high sodium)",
    ],
    keyTip: "Eat small frequent meals with roti, dal, and vegetables. Include karela and methi regularly.",
    sampleMeals: [
      { meal: "Breakfast", foods: "Daliya upma with vegetables, or moong dal chilla with mint chutney" },
      { meal: "Lunch", foods: "2 roti with dal, sabzi (bhindi/lauki), and small bowl curd" },
      { meal: "Dinner", foods: "Brown rice with sambar, palak sabzi, and buttermilk" },
      { meal: "Snacks", foods: "Roasted chana, or cucumber with lemon and chaat masala" },
    ],
  },
  {
    id: "hypertension",
    condition: "High Blood Pressure (Hypertension)",
    category: "heart",
    description: "Low-sodium Indian diet to help control blood pressure naturally.",
    keyFoods: [
      "Fruits (banana, orange, seasonal fruits)",
      "Vegetables (palak, methi, lauki, tori)",
      "Whole grains (brown rice, daliya, oats)",
      "Low-fat dairy (toned milk, curd)",
      "Lean proteins (chicken, fish, dal)",
      "Potassium-rich foods (banana, coconut water)",
      "Garlic and ginger",
      "Jeera and ajwain",
    ],
    avoidFoods: [
      "Namkeen and packaged snacks",
      "Pickles and chutneys (high salt)",
      "Papad and processed foods",
      "Excessive tea and coffee",
      "Fried foods and street food",
      "Salted lassi and buttermilk",
    ],
    keyTip: "Use minimal salt, flavor food with herbs like pudina, dhaniya, and spices like haldi, jeera.",
    sampleMeals: [
      { meal: "Breakfast", foods: "Oats daliya with milk and banana, or poha with vegetables" },
      { meal: "Lunch", foods: "Roti with dal (without tadka), lauki sabzi, and fresh curd" },
      { meal: "Dinner", foods: "Brown rice with rasam, palak dal, and steamed vegetables" },
      { meal: "Snacks", foods: "Fresh fruit, roasted makhana, or coconut water" },
    ],
  },
  {
    id: "heart-disease",
    condition: "Heart Disease",
    category: "heart",
    description: "Heart-healthy Indian diet using affordable local ingredients.",
    keyFoods: [
      "Fish (rohu, katla, sardines)",
      "Mustard oil and groundnut oil (in moderation)",
      "Walnuts and almonds (small portions)",
      "Whole grains (brown rice, daliya, ragi)",
      "Seasonal vegetables and fruits",
      "Moong dal and chana dal",
      "Tomatoes and onions",
      "Garlic and ginger",
    ],
    avoidFoods: [
      "Ghee and butter (excessive)",
      "Red meat and mutton",
      "Refined sugar and jaggery (excess)",
      "Deep fried foods",
      "Coconut oil (excessive)",
      "Processed and packaged foods",
    ],
    keyTip: "Use minimal oil for cooking, include fish twice a week, and eat plenty of vegetables.",
    sampleMeals: [
      { meal: "Breakfast", foods: "Ragi porridge with milk, or vegetable upma with groundnuts" },
      { meal: "Lunch", foods: "Roti with moong dal, mixed vegetable sabzi, and salad" },
      { meal: "Dinner", foods: "Fish curry with brown rice, or dal khichdi with vegetables" },
      { meal: "Snacks", foods: "Roasted groundnuts, seasonal fruit, or vegetable soup" },
    ],
  },
  {
    id: "digestive-ibs",
    condition: "Irritable Bowel Syndrome (IBS)",
    category: "digestive",
    description: "Gentle Indian foods to manage IBS symptoms and improve digestion.",
    keyFoods: [
      "White rice and rice flakes (poha)",
      "Moong dal (peeled) and masoor dal",
      "Curd and buttermilk",
      "Banana and papaya",
      "Bottle gourd (lauki) and ridge gourd (tori)",
      "Ginger and ajwain",
      "Jeera water and fennel tea",
      "Cooked vegetables (avoid raw)",
    ],
    avoidFoods: [
      "Rajma, chole, and heavy dals",
      "Onion and garlic (if sensitive)",
      "Spicy food and red chili",
      "Cabbage and cauliflower",
      "Carbonated drinks",
      "Street food and oily food",
    ],
    keyTip: "Eat simple, home-cooked food. Include ajwain and ginger to aid digestion.",
    sampleMeals: [
      { meal: "Breakfast", foods: "Rice poha with minimal spices, or banana with curd" },
      { meal: "Lunch", foods: "White rice with moong dal, lauki sabzi, and buttermilk" },
      { meal: "Dinner", foods: "Khichdi with ghee, or rice with simple dal and steamed vegetables" },
      { meal: "Snacks", foods: "Banana, jeera water, or rice crackers" },
    ],
  },
  {
    id: "weight-loss",
    condition: "Weight Management",
    category: "weight",
    description: "Affordable Indian diet plan for healthy weight loss.",
    keyFoods: [
      "Vegetables (all types, especially bottle gourd, ridge gourd)",
      "Fruits (papaya, guava, apple, seasonal fruits)",
      "Whole grains (brown rice, daliya, ragi)",
      "Protein (dal, eggs, chicken, fish)",
      "Curd and buttermilk",
      "Green leafy vegetables (palak, methi)",
      "Sprouts (moong, chana)",
      "Green tea and herbal teas",
    ],
    avoidFoods: [
      "Rice and roti (large portions)",
      "Fried foods and pakoras",
      "Sweets and mithai",
      "Cold drinks and juices",
      "Ghee and oil (excessive)",
      "Late night eating",
    ],
    keyTip: "Fill half your plate with vegetables, eat smaller portions, and include physical activity daily.",
    sampleMeals: [
      { meal: "Breakfast", foods: "Vegetable daliya, or moong sprouts with lemon" },
      { meal: "Lunch", foods: "1 roti with dal, large portion of vegetables, and salad" },
      { meal: "Dinner", foods: "Vegetable soup with small portion of khichdi" },
      { meal: "Snacks", foods: "Fruit, roasted chana, or green tea" },
    ],
  },
  {
    id: "kidney-disease",
    condition: "Chronic Kidney Disease",
    category: "kidney",
    description: "Kidney-friendly Indian diet with controlled protein and potassium.",
    keyFoods: [
      "White rice and refined wheat",
      "Small portions of dal (moong, masoor)",
      "Low-potassium vegetables (bottle gourd, ridge gourd)",
      "Apples and pears",
      "Limited curd and milk",
      "Minimal salt and spices",
      "Coconut water (limited)",
      "Boiled and steamed foods",
    ],
    avoidFoods: [
      "Banana and orange (high potassium)",
      "Tomatoes and potatoes (excess)",
      "Dry fruits and nuts",
      "Pickles and namkeen",
      "Dark colored sodas",
      "Excessive protein foods",
    ],
    keyTip: "Limit protein, potassium, and phosphorus. Consult a dietitian for personalized meal planning.",
    sampleMeals: [
      { meal: "Breakfast", foods: "Rice poha with minimal vegetables, or bread with limited butter" },
      { meal: "Lunch", foods: "White rice with small portion dal and bottle gourd sabzi" },
      { meal: "Dinner", foods: "Roti with limited dal and steamed vegetables" },
      { meal: "Snacks", foods: "Apple slices, rice crackers, or limited coconut water" },
    ],
  },
  {
    id: "goitre-thyroid",
    condition: "Goitre & Thyroid Disorders",
    category: "diabetes",
    description: "Thyroid-supporting Indian diet with iodine-rich affordable foods.",
    keyFoods: [
      "Iodized salt (limited quantity)",
      "Fish (sea fish when available)",
      "Dairy products (milk, curd)",
      "Eggs and chicken",
      "Whole grains (brown rice, daliya)",
      "Seasonal fruits and vegetables",
      "Coconut (fresh, limited)",
      "Ginger and turmeric",
    ],
    avoidFoods: [
      "Excessive soy products",
      "Raw cabbage and cauliflower (large amounts)",
      "Processed foods",
      "Excessive tea and coffee",
      "Refined foods and sugar",
      "Millet (bajra) in excess",
    ],
    keyTip: "Use iodized salt in cooking, include sea fish when possible, and maintain regular meal timings.",
    sampleMeals: [
      { meal: "Breakfast", foods: "Milk with daliya, or egg with roti and vegetables" },
      { meal: "Lunch", foods: "Rice with dal, fish curry (when available), and vegetables" },
      { meal: "Dinner", foods: "Roti with chicken/dal, mixed vegetables, and curd" },
      { meal: "Snacks", foods: "Seasonal fruit, milk, or homemade snacks" },
    ],
  },
]
