export interface Disease {
  id: string
  name: string
  category: string
  severity: "mild" | "moderate" | "serious" | "critical"
  description: string
  overview: string
  causes: string[]
  symptoms: string[]
  diagnosis: string[]
  treatment: string[]
  prevention: string[]
  seekHelp: string[]
  relatedConditions?: string[]
}

export const diseases: Disease[] = [
  {
    id: "diabetes-type-2",
    name: "Type 2 Diabetes",
    category: "chronic",
    severity: "serious",
    description:
      "A chronic condition that affects the way your body metabolizes sugar (glucose), your body's important source of fuel.",
    overview:
      "Type 2 diabetes is a chronic metabolic disorder characterized by high blood sugar levels due to insulin resistance and relative insulin deficiency. It is the most common form of diabetes, accounting for about 90-95% of all diabetes cases. The condition develops gradually and is often associated with lifestyle factors such as obesity, physical inactivity, and poor diet.",
    causes: [
      "Insulin resistance in muscle, fat, and liver cells",
      "Genetics and family history",
      "Obesity and excess abdominal fat",
      "Physical inactivity",
      "Age (risk increases after 45)",
      "High blood pressure",
      "Abnormal cholesterol levels",
      "History of gestational diabetes",
    ],
    symptoms: [
      "Increased thirst",
      "Frequent urination",
      "Increased hunger",
      "Unintended weight loss",
      "Fatigue",
      "Blurred vision",
      "Slow-healing sores",
      "Frequent infections",
      "Darkened skin areas",
    ],
    diagnosis: [
      "Fasting plasma glucose test",
      "Oral glucose tolerance test",
      "Hemoglobin A1C test",
      "Random plasma glucose test",
      "Physical examination",
      "Medical history review",
    ],
    treatment: [
      "Lifestyle modifications (diet and exercise)",
      "Metformin (first-line medication)",
      "Other oral diabetes medications",
      "Injectable medications (GLP-1 agonists)",
      "Insulin therapy (if needed)",
      "Regular blood sugar monitoring",
      "Blood pressure management",
      "Cholesterol management",
    ],
    prevention: [
      "Maintain a healthy weight",
      "Exercise regularly (150 minutes per week)",
      "Eat a balanced, nutritious diet",
      "Limit processed foods and sugary drinks",
      "Don't smoke",
      "Limit alcohol consumption",
      "Get regular health screenings",
      "Manage stress levels",
    ],
    seekHelp: [
      "Blood sugar over 400 mg/dL",
      "Signs of diabetic ketoacidosis",
      "Severe dehydration",
      "Persistent vomiting",
      "High fever with diabetes",
      "Confusion or altered mental state",
      "Chest pain or difficulty breathing",
    ],
    relatedConditions: ["Hypertension", "Heart Disease", "Kidney Disease", "Diabetic Retinopathy"],
  },
  {
    id: "hypertension",
    name: "Hypertension (High Blood Pressure)",
    category: "chronic",
    severity: "serious",
    description:
      "A common condition in which the long-term force of blood against artery walls is high enough to cause health problems.",
    overview:
      'Hypertension, commonly known as high blood pressure, is a chronic medical condition where blood pressure in the arteries is persistently elevated. It is often called the "silent killer" because it typically has no symptoms until it causes serious complications. Normal blood pressure is less than 120/80 mmHg, while hypertension is defined as blood pressure consistently above 130/80 mmHg.',
    causes: [
      "Unknown cause (primary hypertension)",
      "Kidney disease",
      "Adrenal gland disorders",
      "Thyroid problems",
      "Sleep apnea",
      "Certain medications",
      "Illegal drugs",
      "Alcohol abuse",
      "Genetics",
    ],
    symptoms: [
      "Usually no symptoms (silent condition)",
      "Headaches (severe cases)",
      "Shortness of breath",
      "Nosebleeds",
      "Flushing",
      "Dizziness",
      "Chest pain",
      "Visual changes",
    ],
    diagnosis: [
      "Multiple blood pressure readings",
      "24-hour ambulatory monitoring",
      "Home blood pressure monitoring",
      "Physical examination",
      "Blood tests (kidney function, cholesterol)",
      "Electrocardiogram (ECG)",
      "Echocardiogram",
      "Urinalysis",
    ],
    treatment: [
      "Lifestyle modifications",
      "ACE inhibitors",
      "Angiotensin receptor blockers (ARBs)",
      "Calcium channel blockers",
      "Diuretics",
      "Beta-blockers",
      "Regular monitoring",
      "Combination therapy if needed",
    ],
    prevention: [
      "Maintain healthy weight",
      "Exercise regularly",
      "Eat a low-sodium diet",
      "Limit alcohol consumption",
      "Don't smoke",
      "Manage stress",
      "Get adequate sleep",
      "Regular blood pressure checks",
    ],
    seekHelp: [
      "Blood pressure over 180/120 mmHg",
      "Severe headache",
      "Chest pain",
      "Difficulty breathing",
      "Vision problems",
      "Confusion",
      "Seizures",
      "Unresponsiveness",
    ],
    relatedConditions: ["Heart Disease", "Stroke", "Kidney Disease", "Type 2 Diabetes"],
  },
  {
    id: "covid-19",
    name: "COVID-19",
    category: "infectious",
    severity: "moderate",
    description: "A respiratory illness caused by the SARS-CoV-2 virus that can range from mild to severe symptoms.",
    overview:
      "COVID-19 (Coronavirus Disease 2019) is an infectious disease caused by the SARS-CoV-2 virus. It primarily affects the respiratory system but can impact multiple organ systems. The virus spreads mainly through respiratory droplets and aerosols when an infected person coughs, sneezes, talks, or breathes. Symptoms can range from mild to severe, and some people may be asymptomatic.",
    causes: [
      "SARS-CoV-2 virus infection",
      "Respiratory droplet transmission",
      "Airborne transmission",
      "Contact with contaminated surfaces",
      "Close contact with infected individuals",
    ],
    symptoms: [
      "Fever or chills",
      "Cough",
      "Shortness of breath",
      "Fatigue",
      "Muscle or body aches",
      "Headache",
      "Loss of taste or smell",
      "Sore throat",
      "Congestion or runny nose",
      "Nausea or vomiting",
      "Diarrhea",
    ],
    diagnosis: [
      "RT-PCR test (molecular test)",
      "Rapid antigen test",
      "Antibody test",
      "Chest X-ray or CT scan",
      "Physical examination",
      "Symptom assessment",
    ],
    treatment: [
      "Rest and hydration (mild cases)",
      "Over-the-counter pain relievers",
      "Antiviral medications (Paxlovid, Remdesivir)",
      "Monoclonal antibodies (high-risk patients)",
      "Oxygen therapy (severe cases)",
      "Hospitalization (severe cases)",
      "Supportive care",
    ],
    prevention: [
      "Get vaccinated and boosted",
      "Wear masks in crowded areas",
      "Practice social distancing",
      "Wash hands frequently",
      "Avoid touching face",
      "Stay home when sick",
      "Improve indoor ventilation",
      "Avoid large gatherings",
    ],
    seekHelp: [
      "Difficulty breathing",
      "Persistent chest pain",
      "Confusion or inability to stay awake",
      "Bluish lips or face",
      "High fever (over 103°F)",
      "Severe dehydration",
      "Worsening symptoms after initial improvement",
    ],
    relatedConditions: ["Pneumonia", "Long COVID", "Acute Respiratory Distress Syndrome"],
  },
  {
    id: "depression",
    name: "Major Depressive Disorder",
    category: "mental",
    severity: "serious",
    description:
      "A mental health disorder characterized by persistent feelings of sadness and loss of interest in activities.",
    overview:
      "Major Depressive Disorder (MDD) is a serious mental health condition that significantly impacts how a person feels, thinks, and handles daily activities. It goes beyond normal sadness and affects millions of people worldwide. The condition can interfere with work, school, relationships, and overall quality of life. It is a treatable condition with proper medical care and support.",
    causes: [
      "Brain chemistry imbalances",
      "Genetics and family history",
      "Hormonal changes",
      "Traumatic life events",
      "Chronic medical conditions",
      "Certain medications",
      "Substance abuse",
      "Seasonal changes",
      "Social isolation",
    ],
    symptoms: [
      "Persistent sad mood",
      "Loss of interest in activities",
      "Significant weight changes",
      "Sleep disturbances",
      "Fatigue or loss of energy",
      "Feelings of worthlessness",
      "Difficulty concentrating",
      "Restlessness or slowed behavior",
      "Thoughts of death or suicide",
    ],
    diagnosis: [
      "Clinical interview",
      "Mental health assessment",
      "Depression screening questionnaires",
      "Physical examination",
      "Blood tests (rule out medical causes)",
      "Psychological evaluation",
      "DSM-5 criteria assessment",
    ],
    treatment: [
      "Psychotherapy (cognitive behavioral therapy)",
      "Antidepressant medications",
      "Combination therapy",
      "Electroconvulsive therapy (severe cases)",
      "Transcranial magnetic stimulation",
      "Lifestyle modifications",
      "Support groups",
      "Regular follow-up care",
    ],
    prevention: [
      "Maintain social connections",
      "Exercise regularly",
      "Get adequate sleep",
      "Eat a healthy diet",
      "Manage stress effectively",
      "Avoid alcohol and drugs",
      "Seek help early",
      "Practice mindfulness or meditation",
    ],
    seekHelp: [
      "Thoughts of suicide or self-harm",
      "Inability to care for yourself",
      "Psychotic symptoms",
      "Severe agitation",
      "Complete social withdrawal",
      "Inability to function at work/school",
      "Substance abuse with depression",
    ],
    relatedConditions: ["Anxiety Disorders", "Bipolar Disorder", "PTSD", "Substance Use Disorders"],
  },
  {
    id: "asthma",
    name: "Asthma",
    category: "respiratory",
    severity: "moderate",
    description: "A respiratory condition where airways narrow and swell, making breathing difficult.",
    overview:
      "Asthma is a chronic respiratory condition that affects the airways in the lungs. During an asthma attack, the airways become inflamed, narrow, and produce extra mucus, making it difficult to breathe. Asthma symptoms can range from minor to life-threatening and can be triggered by various factors including allergens, exercise, cold air, and stress.",
    causes: [
      "Genetic predisposition",
      "Environmental allergens",
      "Respiratory infections",
      "Air pollution",
      "Occupational irritants",
      "Exercise",
      "Weather changes",
      "Strong emotions and stress",
      "Certain medications",
    ],
    symptoms: [
      "Shortness of breath",
      "Chest tightness",
      "Wheezing",
      "Coughing (especially at night)",
      "Difficulty sleeping due to breathing",
      "Rapid breathing",
      "Fatigue during physical activity",
    ],
    diagnosis: [
      "Medical history and physical exam",
      "Spirometry (lung function test)",
      "Peak flow measurement",
      "Chest X-ray",
      "Allergy testing",
      "Exhaled nitric oxide test",
      "Methacholine challenge test",
    ],
    treatment: [
      "Quick-relief inhalers (bronchodilators)",
      "Long-term control medications",
      "Inhaled corticosteroids",
      "Leukotriene modifiers",
      "Long-acting beta agonists",
      "Allergy medications",
      "Immunotherapy (allergy shots)",
      "Asthma action plan",
    ],
    prevention: [
      "Identify and avoid triggers",
      "Take medications as prescribed",
      "Monitor breathing with peak flow meter",
      "Get vaccinated (flu, pneumonia)",
      "Maintain healthy weight",
      "Exercise regularly (with precautions)",
      "Manage allergies",
      "Avoid tobacco smoke",
    ],
    seekHelp: [
      "Severe shortness of breath",
      "Unable to speak in full sentences",
      "Blue lips or fingernails",
      "Extreme anxiety due to breathing",
      "Peak flow readings in red zone",
      "No improvement with rescue inhaler",
      "Chest retractions",
    ],
    relatedConditions: ["Allergic Rhinitis", "Eczema", "COPD", "Sleep Apnea"],
  },
  {
    id: "migraine",
    name: "Migraine Headaches",
    category: "chronic",
    severity: "moderate",
    description:
      "A neurological condition characterized by intense, throbbing headaches often accompanied by other symptoms.",
    overview:
      "Migraine is a complex neurological disorder characterized by recurrent episodes of severe headache, often accompanied by nausea, vomiting, and sensitivity to light and sound. Migraines can last from hours to days and can be so severe that they interfere with daily activities. They affect about 12% of the population and are more common in women than men.",
    causes: [
      "Genetic factors",
      "Hormonal changes",
      "Certain foods and drinks",
      "Stress and anxiety",
      "Sleep changes",
      "Weather changes",
      "Strong smells",
      "Bright lights",
      "Certain medications",
    ],
    symptoms: [
      "Intense throbbing headache",
      "Nausea and vomiting",
      "Sensitivity to light",
      "Sensitivity to sound",
      "Visual disturbances (aura)",
      "Dizziness",
      "Fatigue",
      "Mood changes",
    ],
    diagnosis: [
      "Medical history",
      "Physical and neurological exam",
      "Headache diary",
      "MRI or CT scan (if needed)",
      "Blood tests",
      "International headache criteria",
    ],
    treatment: [
      "Pain-relieving medications",
      "Preventive medications",
      "Triptans for acute attacks",
      "Anti-nausea medications",
      "Lifestyle modifications",
      "Stress management",
      "Biofeedback",
      "Botox injections (chronic migraines)",
    ],
    prevention: [
      "Identify and avoid triggers",
      "Maintain regular sleep schedule",
      "Stay hydrated",
      "Exercise regularly",
      "Manage stress",
      "Eat regular meals",
      "Limit caffeine",
      "Keep a headache diary",
    ],
    seekHelp: [
      "Sudden, severe headache",
      "Headache with fever and stiff neck",
      "Headache after head injury",
      "Chronic headache that worsens",
      "Headache with vision changes",
      "Headache with weakness",
      "New headache pattern after age 50",
    ],
    relatedConditions: ["Tension Headaches", "Cluster Headaches", "Anxiety Disorders"],
  },
]
